Repository VectorInstitute/cyclops, pull requests merged in 2022-12, with the labels that each got.

#299 Update drift work from gemini
  drift_detection/datasets/gemini.py
  drift_detection/drift_detector/detector.py
  drift_detection/drift_detector/rolling_window.py
  drift_detection/drift_detector/tester.py
  drift_detection/drift_detector/utils.py
  drift_detection/gemini/constants.py
  drift_detection/gemini/mortality/constants.py
  drift_detection/gemini/query.py
  drift_detection/gemini/utils.py
  drift_detection/notebooks/drift_experiments/clinical_drift.ipynb
  drift_detection/notebooks/drift_experiments/explainer.ipynb
  drift_detection/notebooks/drift_experiments/synthetic_drift.ipynb
  drift_detection/notebooks/mortality/data_pipeline.ipynb
  drift_detection/notebooks/mortality/preprocessing.ipynb
  drift_detection/notebooks/mortality/static_model.ipynb
  drift_detection/notebooks/mortality/temporal_model.ipynb
  drift_detection/notebooks/mortality_decompensation/data_pipeline.ipynb
  drift_detection/notebooks/retraining/cumulative.ipynb
  drift_detection/notebooks/retraining/local_global.ipynb
  drift_detection/notebooks/retraining/most_recent.ipynb
  drift_detection/retrainers/cumulative.py
  drift_detection/retrainers/mostrecent.py
  tests/drift_detection/drift_detector/test_tester.py
Labels: refactor

#331 Update Use_cases
  use_cases/common/util.py
  use_cases/constants.py
  use_cases/data_collectors/mimiciv/mortality_decompensation.ipynb
  use_cases/data_processors/process.py
  use_cases/examples/mimiciv/mortality_decompensation.ipynb
  use_cases/params/mimiciv/mortality_decompensation/constants.py
  use_cases/params/mimiciv/mortality_decompensation/constants_v1.py
  use_cases/util.py
Labels: refactor

#333 Fixed fractions_to_split fractions mutation bug.
  cyclops/process/feature/split.py
  tests/cyclops/process/feature/test_split.py
Labels: bug

#335 Improve query process ops, add more integration tests
  cyclops/query/process.py
  tests/cyclops/query/test_omop.py
  tests/cyclops/query/test_process.py
Labels: tests

#338 Add more integration tests to query process fns
  cyclops/query/process.py
  tests/cyclops/query/test_process.py
Labels: tests

#339 use models from cyclops/models and delete baseline_models
  cyclops/monitor/baseline_models/__init__.py
  cyclops/monitor/baseline_models/static/__init__.py
  cyclops/monitor/baseline_models/static/ffnn.py
  cyclops/monitor/baseline_models/static/gbt.py
  cyclops/monitor/baseline_models/static/gp.py
  cyclops/monitor/baseline_models/static/lr.py
  cyclops/monitor/baseline_models/static/mlp.py
  cyclops/monitor/baseline_models/static/optimizer.py
  cyclops/monitor/baseline_models/static/rf.py
  cyclops/monitor/baseline_models/static/utils.py
  cyclops/monitor/baseline_models/temporal/__init__.py
  cyclops/monitor/baseline_models/temporal/pytorch/__init__.py
  cyclops/monitor/baseline_models/temporal/pytorch/dataset.py
  cyclops/monitor/baseline_models/temporal/pytorch/metrics.py
  cyclops/monitor/baseline_models/temporal/pytorch/models.py
  cyclops/monitor/baseline_models/temporal/pytorch/utils.py
  cyclops/monitor/optimizer.py
  cyclops/monitor/reductor.py
  cyclops/monitor/retrainers.py
  cyclops/monitor/rolling_window.py
  cyclops/monitor/utils.py
Labels: refactor

#340 Fix docstrings, add additional tests
  cyclops/query/process.py
  tests/cyclops/query/test_process.py
Labels: documentation, tests, code style

#343 Add kwargs to querier, refactor API, improve docs
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  README.md
  cyclops/models/catalog.py
  cyclops/query/base.py
  cyclops/query/gemini.py
  cyclops/query/mimiciv.py
  cyclops/query/omop.py
  cyclops/query/process.py
  cyclops/query/util.py
  docs/source/conf.py
  docs/source/intro.rst
  docs/source/reference/api/cyclops.evaluate.metrics.functional.rst
  docs/source/reference/api/cyclops.evaluate.metrics.rst
  docs/source/reference/api/generated/cyclops.evaluate.metrics.functional.stat_scores.rst
  docs/source/reference/api/generated/cyclops.evaluate.metrics.stat_scores.rst
  docs/source/reference/api/generated/cyclops.query.gemini.rst
  docs/source/reference/api/generated/cyclops.query.mimiciv.rst
  docs/source/reference/api/generated/cyclops.query.omop.rst
  docs/source/reference/api/generated/cyclops.query.process.rst
  tests/cyclops/query/test_omop.py
  tests/cyclops/query/test_process.py
  tests/cyclops/query/test_util.py
Labels: documentation, refactor
