Repository VectorInstitute/cyclops, pull requests merged in 2022-11, with the labels that each got.

#287 Separate out dependencies for docs
  .github/workflows/code_checks.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  pyproject.toml
Labels: documentation

#288 Add docs theme html overrides
  docs/source/_templates/layout.html
  docs/source/theme/breadcrumbs.html
  docs/source/theme/footer.html
  docs/source/theme/layout.html
Labels: documentation

#289 Add slice method to Features, add test
  cyclops/processors/feature/feature.py
  tests/cyclops/processors/feature/test_feature.py
Labels: enhancement, tests

#293 Remove requirements file and environment file
  .github/workflows/code_checks.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  CHANGELOG.md
  README.md
  environment.yml
  poetry.lock
  requirements.txt
Labels: refactor

#294 Update slice method to support slicing across multiple columns
  .pre-commit-config.yaml
  cyclops/processors/feature/feature.py
  tests/cyclops/processors/feature/test_feature.py
Labels: enhancement

#286 Add tests for feature module
  tests/cyclops/processors/feature/test_feature.py
Labels: tests

#297 Remove logging to a log file, just print to stdout
  codebase_ops.py
  cyclops/config.py
  cyclops/orm.py
  cyclops/processors/aggregate.py
  cyclops/processors/clean.py
  cyclops/processors/diagnoses.py
  cyclops/processors/feature/feature.py
  cyclops/processors/feature/vectorize.py
  cyclops/processors/impute.py
  cyclops/processors/util.py
  cyclops/query/gemini.py
  cyclops/query/gemini_omop.py
  cyclops/query/interface.py
  cyclops/query/mimiciv.py
  cyclops/query/process.py
  cyclops/query/util.py
  cyclops/utils/file.py
  cyclops/utils/profile.py
  cyclops/workflow/task.py
  tests/cyclops/utils/test_log.py
Labels: refactor

#295 Add models library
  models/catalog.py
  models/configs/models.yaml
  models/constants.py
  models/data.py
  models/neural_nets/__init__.py
  models/neural_nets/gru.py
  models/neural_nets/lstm.py
  models/neural_nets/mlp.py
  models/neural_nets/rnn.py
  models/plotter.py
  models/predictor.py
  models/utils.py
  models/wrapper.py
Labels: enhancement

#298 Fix bug in slice method
  cyclops/processors/feature/feature.py
  tests/cyclops/processors/feature/test_feature.py
Labels: bug

#301 add metric wrappers & refactor functions
  cyclops/evaluation/metrics/__init__.py
  cyclops/evaluation/metrics/accuracy.py
  cyclops/evaluation/metrics/auroc.py
  cyclops/evaluation/metrics/f_beta.py
  cyclops/evaluation/metrics/functional/__init__.py
  cyclops/evaluation/metrics/functional/accuracy.py
  cyclops/evaluation/metrics/functional/auroc.py
  cyclops/evaluation/metrics/functional/f_beta.py
  cyclops/evaluation/metrics/functional/precision_recall.py
  cyclops/evaluation/metrics/functional/precision_recall_curve.py
  cyclops/evaluation/metrics/functional/roc.py
  cyclops/evaluation/metrics/functional/sensitivity.py
  cyclops/evaluation/metrics/functional/specificity.py
  cyclops/evaluation/metrics/functional/stat_scores.py
  cyclops/evaluation/metrics/metric.py
  cyclops/evaluation/metrics/precision_recall.py
  cyclops/evaluation/metrics/precision_recall_curve.py
  cyclops/evaluation/metrics/roc.py
  cyclops/evaluation/metrics/sensitivity.py
  cyclops/evaluation/metrics/specificity.py
  cyclops/evaluation/metrics/stat_scores.py
  cyclops/evaluation/metrics/utils.py
  tests/cyclops/evaluation/metrics/helpers.py
  tests/cyclops/evaluation/metrics/test_accuracy.py
  tests/cyclops/evaluation/metrics/test_auroc.py
  tests/cyclops/evaluation/metrics/test_fbeta.py
  tests/cyclops/evaluation/metrics/test_precision_recall.py
  tests/cyclops/evaluation/metrics/test_precision_recall_curve.py
  tests/cyclops/evaluation/metrics/test_roc.py
  tests/cyclops/evaluation/metrics/test_specificity.py
  tests/cyclops/evaluation/metrics/test_stat_scores.py
Labels: enhancement, refactor

#306 Standardize data layer
  .gitignore
  drift_detection/configs/detector/NIHCXR-txrv_ae-mmd.yaml
  drift_detection/configs/detector/gemini/dataframe_mapping.yaml
  drift_detection/configs/gemini/hospital_type_academic.yaml
  drift_detection/configs/nihcxr/baseline.yaml
  drift_detection/configs/nihcxr/categorical_gender_F.yaml
  drift_detection/configs/nihcxr/categorical_gender_M.yaml
  drift_detection/configs/nihcxr/categorical_targets_Mass.yaml
  drift_detection/configs/nihcxr/categorical_targets_age_70-100.yaml
  drift_detection/configs/nihcxr/synthetic_gaussian.yaml
  drift_detection/datasets/__init__.py
  drift_detection/datasets/configs/gemini.yaml
  drift_detection/datasets/configs/nihcxr.yaml
  drift_detection/datasets/gemini.py
  drift_detection/datasets/nihcxr.py
  drift_detection/drift_detector/__init__.py
  drift_detection/drift_detector/clinical_applicator.py
  drift_detection/drift_detector/detector.py
  drift_detection/drift_detector/experimenter.py
  drift_detection/drift_detector/rolling_window.py
  drift_detection/drift_detector/synthetic_applicator.py
  drift_detection/drift_detector/tester.py
  drift_detection/drift_detector/utils.py
  drift_detection/gemini/utils.py
  drift_detection/gemini_drift_detection.py
  drift_detection/notebooks/nihcxr_drift_experiments/nihcxr_synthetic_drift_categorical.ipynb
  drift_detection/notebooks/nihcxr_drift_experiments/nihcxr_synthetic_drift_gaussian.ipynb
  drift_detection/run_drift_detection.py
  pyproject.toml
Labels: refactor

#309 Rename ci workflows
  .github/workflows/code_checks.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  README.md
Labels: documentation

#310 Fixes after rename
  README.md
  cyclops/query/base.py
  use_cases/common/2.1-tabular_processing.ipynb
  use_cases/common/2.2-temporal_processing.ipynb
  use_cases/common/3.1-tabular_model.ipynb
  use_cases/common/3.2-temporal_model.ipynb
  use_cases/mimiciv/mortality_decompensation/1-query.ipynb
Labels: refactor

#312 Remove use of singleton for Database class
  cyclops/query/orm.py
  cyclops/query/util.py
  tests/cyclops/query/test_mimiciv.py
Labels: enhancement, tests, refactor
