Repository VectorInstitute/cyclops, pull requests merged in 2023-05, with the labels that each got.

#423 Remove pre-run cells and have tutorial nb run during docs build in CI
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  docs/source/tutorials/eicu/query_api.ipynb
  docs/source/tutorials/mimiciii/query_api.ipynb
  docs/source/tutorials/mimiciv/query_api.ipynb
  docs/source/tutorials/nihcxr/monitor_api.ipynb
  docs/source/tutorials/omop/query_api.ipynb
  poetry.lock
  pyproject.toml
Labels: documentation, tests

#424 Add ipywidgets to deps
  README.md
  docs/source/contributing.md
  docs/source/contributing.rst
  docs/source/intro.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#425 Add retry to codecov action when it fails
  .github/workflows/docs_deploy.yml
  README.md
  docs/source/intro.rst
  poetry.lock
  pyproject.toml
Labels: enhancement, tests

#428 Update models
  cyclops/models/catalog.py
  cyclops/models/configs/densenet.yaml
  cyclops/models/configs/gru.yaml
  cyclops/models/configs/logistic_regression.yaml
  cyclops/models/configs/lstm.yaml
  cyclops/models/configs/mlp.yaml
  cyclops/models/configs/rf_classifier.yaml
  cyclops/models/configs/sgd_classifier.yaml
  cyclops/models/configs/xgb_classifier.yaml
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/sk_model.py
  use_cases/cxr_classification.ipynb
  use_cases/mortality_prediction.ipynb
Labels: enhancement, refactor

#427 Add Report package
  cyclops/report/__init__.py
  cyclops/report/examples/cyclops_mock_template.ipynb
  cyclops/report/model_card/model_card.py
  cyclops/report/model_card/schema/v0.0.1/model_card_schema.json
  cyclops/report/model_card/template/cyclops_template.jinja
  cyclops/report/report.py
  pyproject.toml
Labels: enhancement

#429 Move notebooks to nbs dir to avoid confusion
  nbs/monitor/gemini_drift_experiments/clinical_drift.ipynb
  nbs/monitor/gemini_drift_experiments/explainer.ipynb
  nbs/monitor/gemini_drift_experiments/feature_shift.ipynb
  nbs/monitor/gemini_drift_experiments/synthetic_drift.ipynb
  nbs/monitor/mortality/data_pipeline.ipynb
  nbs/monitor/mortality/preprocessing.ipynb
  nbs/monitor/mortality/static_model.ipynb
  nbs/monitor/mortality/temporal_model.ipynb
  nbs/monitor/retraining/confidence.ipynb
  nbs/monitor/retraining/cumulative.ipynb
  nbs/monitor/retraining/local_global.ipynb
  nbs/monitor/retraining/most_recent.ipynb
  nbs/monitor/rolling_window/hosp_type.ipynb
  nbs/monitor/rolling_window/static.ipynb
  nbs/monitor/rolling_window/temporal.ipynb
Labels: documentation
