Repository VectorInstitute/cyclops, pull requests merged in 2023-12, with the labels that each got.

#522 Fix metrics examples, add average precision metric
  .pre-commit-config.yaml
  cyclops/evaluate/metrics/__init__.py
  cyclops/evaluate/metrics/accuracy.py
  cyclops/evaluate/metrics/auroc.py
  cyclops/evaluate/metrics/average_precision.py
  cyclops/evaluate/metrics/experimental/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/distributed_backends/base.py
  cyclops/evaluate/metrics/experimental/distributed_backends/mpi4py.py
  cyclops/evaluate/metrics/experimental/functional/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/metric.py
  cyclops/evaluate/metrics/experimental/utils/__init__.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  cyclops/evaluate/metrics/experimental/utils/types.py
  cyclops/evaluate/metrics/experimental/utils/validation.py
  cyclops/evaluate/metrics/f_beta.py
  cyclops/evaluate/metrics/functional/__init__.py
  cyclops/evaluate/metrics/functional/accuracy.py
  cyclops/evaluate/metrics/functional/auroc.py
  cyclops/evaluate/metrics/functional/average_precision.py
  cyclops/evaluate/metrics/functional/f_beta.py
  cyclops/evaluate/metrics/functional/precision_recall.py
  cyclops/evaluate/metrics/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/functional/roc.py
  cyclops/evaluate/metrics/functional/sensitivity.py
  cyclops/evaluate/metrics/functional/specificity.py
  cyclops/evaluate/metrics/functional/stat_scores.py
  cyclops/evaluate/metrics/precision_recall.py
  cyclops/evaluate/metrics/precision_recall_curve.py
  cyclops/evaluate/metrics/roc.py
  cyclops/evaluate/metrics/sensitivity.py
  cyclops/evaluate/metrics/specificity.py
  cyclops/evaluate/metrics/stat_scores.py
  cyclops/models/wrappers/sk_model.py
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  tests/cyclops/evaluate/metrics/experimental/inputs.py
  tests/cyclops/evaluate/metrics/experimental/test_operator_metric.py
  tests/cyclops/evaluate/metrics/experimental/testers.py
  tests/cyclops/evaluate/metrics/test_auroc.py
  tests/cyclops/evaluate/metrics/test_average_precision.py
Labels: documentation, enhancement

#523 Add accuracy metric
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/accuracy.py
  cyclops/evaluate/metrics/experimental/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/distributed_backends/base.py
  cyclops/evaluate/metrics/experimental/distributed_backends/mpi4py.py
  cyclops/evaluate/metrics/experimental/distributed_backends/torch_distributed.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/_stat_scores.py
  cyclops/evaluate/metrics/experimental/functional/accuracy.py
  cyclops/evaluate/metrics/experimental/functional/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/metric.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  cyclops/evaluate/metrics/experimental/utils/types.py
  cyclops/evaluate/metrics/experimental/utils/validation.py
  tests/cyclops/evaluate/metrics/experimental/inputs.py
  tests/cyclops/evaluate/metrics/experimental/test_accuracy.py
  tests/cyclops/evaluate/metrics/experimental/test_confusion_matrix.py
  tests/cyclops/evaluate/metrics/experimental/testers.py
Labels: enhancement, refactor

#525 Add precision and recall
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/accuracy.py
  cyclops/evaluate/metrics/experimental/functional/precision_recall.py
  cyclops/evaluate/metrics/experimental/precision_recall.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  tests/cyclops/evaluate/metrics/experimental/test_accuracy.py
  tests/cyclops/evaluate/metrics/experimental/test_precision_recall.py
Labels: enhancement, refactor

#528 Patch array formatting for metrics
  cyclops/evaluate/metrics/utils.py
Labels: refactor

#529 Add some unit tests for the ModelCardReport methods
  .pre-commit-config.yaml
  cyclops/data/slicer.py
  cyclops/monitor/clinical_applicator.py
  cyclops/monitor/reductor.py
  cyclops/monitor/synthetic_applicator.py
  cyclops/monitor/tester.py
  cyclops/report/report.py
  cyclops/report/utils.py
  tests/cyclops/report/test_report.py
Labels: tests

#530 Remove outdated notebooks, add first ICU mortality prediction benchmark
  .pre-commit-config.yaml
  benchmarks/mimiciv/icu_mortality_prediction.ipynb
  nbs/explore_huggingface_datasets.ipynb
  nbs/monitor/mortality/static_model.ipynb
  nbs/monitor/mortality/temporal_model.ipynb
  use_cases/common/2.1-tabular_processing.ipynb
  use_cases/common/2.2-temporal_processing.ipynb
  use_cases/common/3.1-tabular_model.ipynb
  use_cases/common/3.2-temporal_model.ipynb
Labels: documentation, enhancement

#532 Add unit tests for some utils functions used in data package
  tests/cyclops/data/test_utils.py
Labels: tests

#533 Add `MetricDict`
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/metric.py
  cyclops/evaluate/metrics/experimental/metric_dict.py
  tests/cyclops/evaluate/metrics/experimental/test_metric_dict.py
  tests/cyclops/evaluate/metrics/experimental/testers.py
Labels: enhancement, refactor

#534 Fix mypy issue by adding plugin, add tests
  .pre-commit-config.yaml
  cyclops/models/__init__.py
  cyclops/models/catalog.py
  cyclops/models/configs/mlp_classifier.yaml
  cyclops/models/wrappers/sk_model.py
  poetry.lock
  pyproject.toml
  tests/cyclops/models/wrappers/test_sk_model.py
  tests/cyclops/models/wrappers/test_utils.py
  tests/cyclops/tasks/test_classification.py
Labels: tests

#536 Add Specificity
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/specificity.py
  cyclops/evaluate/metrics/experimental/specificity.py
  tests/cyclops/evaluate/metrics/experimental/test_specificity.py
Labels: enhancement

#537 Add aliases for precision and recall
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/precision_recall.py
  cyclops/evaluate/metrics/experimental/precision_recall.py
Labels: enhancement

#540 Relax numpy version, fix integration test
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  poetry.lock
  pyproject.toml
Labels: update

#541 Add True Negative Rate (TNR)
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/specificity.py
  cyclops/evaluate/metrics/experimental/specificity.py
Labels: enhancement
