Repository VectorInstitute/cyclops, pull requests merged in 2023-03, with the labels that each got.

#391 Add Hugging Face datasets
  .pre-commit-config.yaml
  cyclops/datasets/__init__.py
  cyclops/datasets/features/__init__.py
  cyclops/datasets/features/medical_image.py
  cyclops/datasets/packaged_loading_scripts/medical_imagefolder/__init__.py
  cyclops/datasets/packaged_loading_scripts/medical_imagefolder/medical_imagefolder.py
  cyclops/datasets/slicing.py
  cyclops/evaluate/metrics/roc.py
  cyclops/models/__init__.py
  cyclops/models/utils.py
  cyclops/monitor/clinical_applicator.py
  cyclops/monitor/datasets/gemini.py
  cyclops/monitor/datasets/nihcxr.py
  cyclops/monitor/detector.py
  cyclops/monitor/experimenter.py
  cyclops/monitor/gemini/utils.py
  cyclops/monitor/reductor.py
  cyclops/monitor/retrainers.py
  cyclops/monitor/rolling_window.py
  cyclops/monitor/synthetic_applicator.py
  cyclops/monitor/utils.py
  cyclops/utils/common.py
  nbs/explore_huggingface_datasets.ipynb
  poetry.lock
  pyproject.toml
  tests/cyclops/datasets/test_slicing.py
  use_cases/data_processors/mimiciv.py
Labels: enhancement

#393 Monitor integrate dataset api
  cyclops/evaluate/slicing.py
  cyclops/monitor/clinical_applicator.py
  cyclops/monitor/experimenter.py
  cyclops/monitor/reductor.py
  cyclops/monitor/run_drift_detection.py
  cyclops/monitor/synthetic_applicator.py
  cyclops/monitor/utils.py
  tests/cyclops/monitor/synthetic_datasets.py
  tests/cyclops/monitor/test_clinical_applicator.py
  tests/cyclops/monitor/test_experimenter.py
  tests/cyclops/monitor/test_reductor.py
  tests/cyclops/monitor/test_synthetic_applicator.py
  tutorials/monitor/nihcxr_drift_experiments/nihcxr_synthetic_drift_categorical.ipynb
Labels: enhancement, refactor

#389 Add mypy checks for evaluate package
  .pre-commit-config.yaml
  cyclops/evaluate/metrics/accuracy.py
  cyclops/evaluate/metrics/auroc.py
  cyclops/evaluate/metrics/f_beta.py
  cyclops/evaluate/metrics/functional/accuracy.py
  cyclops/evaluate/metrics/functional/auroc.py
  cyclops/evaluate/metrics/functional/f_beta.py
  cyclops/evaluate/metrics/functional/precision_recall.py
  cyclops/evaluate/metrics/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/functional/roc.py
  cyclops/evaluate/metrics/functional/sensitivity.py
  cyclops/evaluate/metrics/functional/specificity.py
  cyclops/evaluate/metrics/functional/stat_scores.py
  cyclops/evaluate/metrics/metric.py
  cyclops/evaluate/metrics/precision_recall.py
  cyclops/evaluate/metrics/precision_recall_curve.py
  cyclops/evaluate/metrics/roc.py
  cyclops/evaluate/metrics/specificity.py
  cyclops/evaluate/metrics/stat_scores.py
  cyclops/evaluate/metrics/utils.py
  cyclops/evaluate/slicing.py
  cyclops/monitor/clinical_applicator.py
  poetry.lock
  pyproject.toml
Labels: code style

#394 Update API docs for evaluate and datasets modules
  cyclops/evaluate/metrics/functional/__init__.py
  docs/source/reference/api/cyclops.evaluate.metrics.functional.rst
  docs/source/reference/api/cyclops.evaluate.metrics.rst
  docs/source/reference/api/cyclops.evaluate.rst
  docs/source/reference/api/cyclops.query.rst
Labels: documentation

#397 Add query to take union of two queries
  cyclops/query/ops.py
  tests/cyclops/query/test_ops.py
Labels: enhancement, refactor

#401 Add select distinct as a query op
  cyclops/query/interface.py
  cyclops/query/ops.py
  tests/cyclops/query/test_ops.py
Labels: enhancement

#403 Integrate model module
  cyclops/monitor/__init__.py
  cyclops/monitor/clinical_applicator.py
  cyclops/monitor/configs/gemini/hospital_type_academic.yaml
  cyclops/monitor/configs/nihcxr/baseline.yaml
  cyclops/monitor/configs/nihcxr/categorical_gender_F.yaml
  cyclops/monitor/configs/nihcxr/categorical_gender_M.yaml
  cyclops/monitor/configs/nihcxr/categorical_targets_Mass.yaml
  cyclops/monitor/configs/nihcxr/categorical_targets_age_70-100.yaml
  cyclops/monitor/configs/nihcxr/synthetic_gaussian.yaml
  cyclops/monitor/datasets/__init__.py
  cyclops/monitor/datasets/configs/gemini.yaml
  cyclops/monitor/datasets/configs/nihcxr.yaml
  cyclops/monitor/datasets/gemini.py
  cyclops/monitor/datasets/nihcxr.py
  cyclops/monitor/datasets/utils.py
  cyclops/monitor/detector.py
  cyclops/monitor/experimenter.py
  cyclops/monitor/reductor.py
  cyclops/monitor/run_drift_detection.py
  cyclops/monitor/synthetic_applicator.py
  cyclops/monitor/tester.py
  cyclops/monitor/utils.py
  cyclops/process/feature/handle_types.py
  cyclops/query/util.py
  tests/cyclops/monitor/synthetic_datasets.py
  tests/cyclops/monitor/test_detector.py
  tests/cyclops/monitor/test_experimenter.py
  tests/cyclops/monitor/test_reductor.py
  tests/cyclops/monitor/test_tester.py
  tutorials/monitor/nihcxr_drift_experiments/NIHCXR Clinical Drift.ipynb
  tutorials/monitor/nihcxr_drift_experiments/nihcxr_synthetic_drift_categorical.ipynb
  tutorials/monitor/nihcxr_drift_experiments/nihcxr_synthetic_drift_gaussian.ipynb
Labels: refactor

#406 Tasks
  .pre-commit-config.yaml
  cyclops/datasets/utils.py
  cyclops/models/__init__.py
  cyclops/models/catalog.py
  cyclops/models/configs/densenet.yaml
  cyclops/models/configs/mlp.yaml
  cyclops/models/configs/resnet.yaml
  cyclops/models/data.py
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/sk_model.py
  cyclops/monitor/utils.py
  cyclops/tasks/cxr_classification.py
  cyclops/tasks/mortality_prediction.py
  cyclops/tasks/utils.py
  poetry.lock
  pyproject.toml
  use_cases/cxr_classification.ipynb
  use_cases/mortality_prediction.ipynb
  use_cases/util.py
Labels: enhancement, refactor
