Repository VectorInstitute/cyclops, pull requests merged in 2023-04, with the labels that each got.

#410 Integrate evaluate and models
  cyclops/evaluate/evaluator.py
  cyclops/evaluate/fairness/evaluator.py
  cyclops/models/__init__.py
  cyclops/models/catalog.py
  cyclops/models/configs/rf_classifier.yaml
  cyclops/models/configs/sgd_classifier.yaml
  cyclops/models/configs/xgb_classifier.yaml
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/sk_model.py
  cyclops/tasks/mortality_prediction.py
  nbs/explore_huggingface_datasets.ipynb
  poetry.lock
  pyproject.toml
Labels: enhancement, refactor

#390 Add mypy checks for monitor package
  cyclops/monitor/clinical_applicator.py
  cyclops/monitor/detector.py
  cyclops/monitor/explainer.py
  cyclops/monitor/gemini/mortality/constants.py
  cyclops/monitor/gemini/utils.py
  cyclops/monitor/optimizer.py
  cyclops/monitor/plotter.py
  cyclops/monitor/reductor.py
  cyclops/monitor/retrainers.py
  cyclops/monitor/rolling_window.py
  cyclops/monitor/synthetic_applicator.py
  cyclops/monitor/tester.py
  cyclops/monitor/utils.py
  tests/cyclops/monitor/test_tester.py
  tutorials/monitor/nihcxr_drift_experiments/NIHCXR Clinical Drift.ipynb
Labels: code style

#414 Improve the apply function to take multiple arguments (columns) and a…
  cyclops/query/ops.py
  tests/cyclops/query/test_ops.py
Labels: enhancement
