Repository VectorInstitute/cyclops, pull requests merged in 2023-11, with the labels that each got.

#497 Remove use of dask, update to pandas 2.0, fix tests
  README.md
  cyclops/process/feature/feature.py
  cyclops/process/feature/handle_types.py
  cyclops/utils/file.py
  docs/source/intro.rst
  poetry.lock
  pyproject.toml
  tests/cyclops/process/feature/test_handle_types.py
  tests/cyclops/utils/test_file.py
  use_cases/cxr_classification.ipynb
Labels: tests, refactor

#496 Report Template Update
  cyclops/data/loader.py
  cyclops/monitor/detector.py
  cyclops/report/model_card/fields.py
  cyclops/report/model_card/model_card.py
  cyclops/report/model_card/sections.py
  cyclops/report/report.py
  cyclops/report/templates/cyclops_generic_template.jinja
  cyclops/report/templates/cyclops_generic_template_light.jinja
  cyclops/report/utils.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/nihcxr/generate_nihcxr_report.py
  docs/source/tutorials/synthea/los_prediction.ipynb
  tests/cyclops/report/test_utils.py
Labels: enhancement

#498 added model info card to sidebar
  cyclops/report/templates/cyclops_generic_template.jinja
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
Labels: enhancement

#500 Update model report links
  README.md
  docs/source/intro.rst
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
Labels: bug, documentation

#501 Add separate classes for classification tasks
  cyclops/models/wrappers/base.py
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/sk_model.py
  cyclops/tasks/__init__.py
  cyclops/tasks/base.py
  cyclops/tasks/classification.py
  cyclops/tasks/cxr_classification.py
  cyclops/tasks/mortality_prediction.py
  cyclops/utils/file.py
  tests/cyclops/tasks/test_classification.py
  tests/cyclops/tasks/test_cxr_classification.py
  tests/cyclops/tasks/test_mortality_prediction.py
Labels: refactor

#503 Fix typing for kwargs parameter in create_metric_fn
  .gitignore
  cyclops/evaluate/metrics/factory.py
  docs/source/tutorials/nihcxr/generate_nihcxr_report.py
Labels: code style

#499 Add experimental metrics package following the array API standard
  .github/workflows/integration_tests.yml
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/distributed_backends/__init__.py
  cyclops/evaluate/metrics/experimental/distributed_backends/base.py
  cyclops/evaluate/metrics/experimental/distributed_backends/mpi4py.py
  cyclops/evaluate/metrics/experimental/distributed_backends/non_distributed.py
  cyclops/evaluate/metrics/experimental/distributed_backends/torch_distributed.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/metric.py
  cyclops/evaluate/metrics/experimental/utils/__init__.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  cyclops/evaluate/metrics/experimental/utils/typing.py
  cyclops/evaluate/metrics/experimental/utils/validation.py
  cyclops/utils/optional.py
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/__init__.py
  tests/cyclops/evaluate/metrics/__init__.py
  tests/cyclops/evaluate/metrics/conftest.py
  tests/cyclops/evaluate/metrics/experimental/__init__.py
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/__init__.py
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_mpi4py.py
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_torch_distributed.py
  tests/cyclops/evaluate/metrics/experimental/inputs.py
  tests/cyclops/evaluate/metrics/experimental/test_confusion_matrix.py
  tests/cyclops/evaluate/metrics/experimental/test_metric.py
  tests/cyclops/evaluate/metrics/experimental/test_operator_metric.py
  tests/cyclops/evaluate/metrics/experimental/testers.py
  tests/cyclops/evaluate/metrics/experimental/utils/test_ops.py
  tests/cyclops/evaluate/metrics/experimental/utils/test_validation.py
  tests/cyclops/evaluate/metrics/inputs.py
  tests/cyclops/evaluate/metrics/test_accuracy.py
  tests/cyclops/evaluate/metrics/test_auroc.py
  tests/cyclops/evaluate/metrics/test_fbeta.py
  tests/cyclops/evaluate/metrics/test_metric_collection.py
  tests/cyclops/evaluate/metrics/test_precision_recall.py
  tests/cyclops/evaluate/metrics/test_precision_recall_curve.py
  tests/cyclops/evaluate/metrics/test_roc.py
  tests/cyclops/evaluate/metrics/test_specificity.py
  tests/cyclops/evaluate/metrics/test_stat_scores.py
  tests/cyclops/utils/test_optional.py
Labels: enhancement, refactor

#505 Clean up process package fns, enable mypy
  .pre-commit-config.yaml
  cyclops/process/aggregate.py
  cyclops/process/clean.py
  cyclops/process/column_names.py
  cyclops/process/constants.py
  cyclops/process/diagnoses.py
  cyclops/process/feature/feature.py
  cyclops/process/feature/handle_types.py
  cyclops/process/feature/normalize.py
  cyclops/process/feature/split.py
  cyclops/process/feature/vectorized.py
  cyclops/process/impute.py
  cyclops/process/string_ops.py
  cyclops/process/util.py
  cyclops/utils/common.py
  tests/cyclops/process/feature/test_feature.py
  tests/cyclops/process/feature/test_normalize.py
  tests/cyclops/process/test_aggregate.py
  tests/cyclops/process/test_clean.py
  tests/cyclops/process/test_impute.py
  tests/cyclops/process/test_util.py
Labels: refactor

#508 Fix tasks doc
  docs/source/reference/api/cyclops.tasks.rst
Labels: documentation

#509 Minor improvements to the evaluators and metrics
  cyclops/evaluate/evaluator.py
  cyclops/evaluate/fairness/evaluator.py
  cyclops/evaluate/metrics/accuracy.py
  cyclops/evaluate/metrics/auroc.py
  cyclops/evaluate/metrics/experimental/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/metric.py
  cyclops/evaluate/metrics/f_beta.py
  cyclops/evaluate/metrics/metric.py
  cyclops/evaluate/metrics/precision_recall.py
  cyclops/evaluate/metrics/precision_recall_curve.py
  cyclops/evaluate/metrics/roc.py
  cyclops/evaluate/metrics/sensitivity.py
  cyclops/evaluate/metrics/specificity.py
  cyclops/evaluate/metrics/stat_scores.py
  tests/cyclops/evaluate/metrics/experimental/test_operator_metric.py
Labels: refactor

#506 Reorganize package dependencies
  .github/workflows/package.yml
  README.md
  cyclops/data/features/medical_image.py
  cyclops/data/packaged_loading_scripts/medical_imagefolder/medical_imagefolder.py
  cyclops/data/transforms.py
  cyclops/evaluate/metrics/experimental/distributed_backends/mpi4py.py
  cyclops/evaluate/metrics/experimental/distributed_backends/torch_distributed.py
  cyclops/models/wrappers/pt_model.py
  cyclops/monitor/reductor.py
  cyclops/monitor/tester.py
  cyclops/tasks/classification.py
  cyclops/utils/optional.py
  docs/source/intro.rst
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/nihcxr/generate_nihcxr_report.py
  docs/source/tutorials/nihcxr/monitor_api.ipynb
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/metrics/conftest.py
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_mpi4py.py
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_torch_distributed.py
  tests/cyclops/evaluate/metrics/experimental/utils/test_ops.py
  tests/cyclops/utils/test_optional.py
  tests/package/base.py
  tests/package/extras/models.py
  tests/package/extras/report.py
Labels: refactor

#511 Add confusion matrix example to tutorial notebook
  cyclops/models/plotter.py
  cyclops/models/predictor.py
  cyclops/models/utils.py
  cyclops/report/plot/classification.py
  cyclops/tasks/classification.py
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
Labels: documentation

#514 Small fix to notebooks
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
Labels: documentation

#516 Decouple models from evaluate package
  cyclops/data/utils.py
  cyclops/evaluate/evaluator.py
  cyclops/evaluate/fairness/evaluator.py
  cyclops/evaluate/utils.py
  cyclops/tasks/classification.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/nihcxr/generate_nihcxr_report.py
  docs/source/tutorials/synthea/los_prediction.ipynb
Labels: refactor

#515 Make additional library dependencies optional
  .github/workflows/code_checks.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  .github/workflows/package.yml
  README.md
  cyclops/data/transforms.py
  cyclops/data/utils.py
  cyclops/models/__init__.py
  cyclops/models/catalog.py
  cyclops/models/constants.py
  cyclops/models/data.py
  cyclops/models/neural_nets/__init__.py
  cyclops/models/neural_nets/gru.py
  cyclops/models/neural_nets/lstm.py
  cyclops/models/neural_nets/mlp.py
  cyclops/models/neural_nets/rnn.py
  cyclops/models/torch_utils.py
  cyclops/models/utils.py
  cyclops/models/wrappers/__init__.py
  cyclops/models/wrappers/base.py
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/utils.py
  cyclops/monitor/__init__.py
  cyclops/monitor/explainer.py
  cyclops/monitor/reductor.py
  cyclops/monitor/tester.py
  cyclops/monitor/utils.py
  cyclops/tasks/base.py
  cyclops/tasks/classification.py
  cyclops/tasks/utils.py
  cyclops/utils/plot.py
  docs/source/intro.rst
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/metrics/conftest.py
  tests/cyclops/models/test_torch_utils.py
  tests/cyclops/monitor/test_reductor.py
  tests/package/base.py
  tests/package/extras/models.py
Labels: refactor

#517 make sections collapsible and set default as collapsed
  cyclops/report/templates/cyclops_generic_template.jinja
Labels: enhancement

#519 Unify process package into data
  cyclops/data/aggregate.py
  cyclops/data/clean.py
  cyclops/data/constants.py
  cyclops/data/df/__init__.py
  cyclops/data/df/feature.py
  cyclops/data/df/handle_types.py
  cyclops/data/df/normalize.py
  cyclops/data/df/split.py
  cyclops/data/df/vectorized.py
  cyclops/data/diagnoses.py
  cyclops/data/impute.py
  cyclops/data/string_ops.py
  cyclops/data/utils.py
  cyclops/process/__init__.py
  cyclops/process/util.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  pyproject.toml
  tests/cyclops/data/df/__init__.py
  tests/cyclops/data/df/test_feature.py
  tests/cyclops/data/df/test_handle_types.py
  tests/cyclops/data/df/test_normalize.py
  tests/cyclops/data/df/test_split.py
  tests/cyclops/data/df/test_vectorized.py
  tests/cyclops/data/test_aggregate.py
  tests/cyclops/data/test_clean.py
  tests/cyclops/data/test_diagnoses.py
  tests/cyclops/data/test_impute.py
  tests/cyclops/data/test_string_ops.py
  tests/cyclops/data/test_utils.py
  tests/cyclops/process/__init__.py
  tests/package/base.py
Labels: refactor
