Repository VectorInstitute/cyclops, pull requests merged in 2023-09, with the labels that each got.

#477 Improve query ops API, update deps
  .github/workflows/docs_build.yml
  .github/workflows/integration_tests.yml
  codecov.yml
  cyclops/evaluate/metrics/utils.py
  cyclops/monitor/utils.py
  cyclops/query/interface.py
  cyclops/query/ops.py
  cyclops/query/util.py
  cyclops/report/report.py
  docs/source/tutorials/eicu/query_api.ipynb
  docs/source/tutorials/gemini/query_api.ipynb
  docs/source/tutorials/mimiciii/query_api.ipynb
  docs/source/tutorials/mimiciv/query_api.ipynb
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/nihcxr/monitor_api.ipynb
  docs/source/tutorials/omop/query_api.ipynb
  poetry.lock
  pyproject.toml
  tests/cyclops/query/test_ops.py
  tests/cyclops/query/test_util.py
Labels: bug, documentation, refactor

#480 Add few tests, update codecov yml
  codecov.yml
  cyclops/query/ops.py
  tests/cyclops/query/test_ops.py
Labels: tests

#481 Make it optional to include overall slice in SliceSpec
  cyclops/data/slicer.py
Labels: refactor

#482 Monitor: detectron implementation
  cyclops/data/loader.py
  cyclops/data/preprocess.py
  cyclops/data/utils.py
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/sk_model.py
  cyclops/models/wrappers/utils.py
  cyclops/monitor/clinical_applicator.py
  cyclops/monitor/detector.py
  cyclops/monitor/reductor.py
  cyclops/monitor/tester.py
  cyclops/monitor/utils.py
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/nihcxr/monitor_api.ipynb
  tests/cyclops/monitor/synthetic_datasets.py
  tests/cyclops/monitor/test_detector.py
  tests/cyclops/monitor/test_reductor.py
  tests/cyclops/monitor/test_tester.py
Labels: enhancement

#484 monitor: remove unused packages
  cyclops/monitor/dataframe_mapping.py
  cyclops/monitor/gemini/__init__.py
  cyclops/monitor/gemini/mortality/constants.py
  cyclops/monitor/gemini/query.py
  cyclops/monitor/gemini/utils.py
  cyclops/monitor/optimizer.py
  cyclops/monitor/retrainers.py
  cyclops/monitor/rolling_window.py
Labels: refactor

#489 Update gemini query nb
  cyclops/query/ops.py
  docs/source/tutorials/gemini/query_api.ipynb
  poetry.lock
  tests/cyclops/query/test_ops.py
Labels: documentation
