Repository VectorInstitute/cyclops, pull requests merged in 2023-08, with the labels that each got.

#466 fix formatting for tests
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .gitignore
  cyclops/report/templates/cyclops_generic_template_light.jinja
Labels: enhancement

#474 Initial clean up, update precommit tools
  .pre-commit-config.yaml
  cyclops/__init__.py
  cyclops/evaluate/fairness/evaluator.py
  cyclops/models/wrappers/pt_model.py
  cyclops/process/feature/handle_types.py
  cyclops/query/eicu.py
  cyclops/query/ops.py
  cyclops/tasks/mortality_prediction.py
  cyclops/tasks/utils.py
  cyclops/workflow/__init__.py
  cyclops/workflow/constants.py
  cyclops/workflow/task.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  docs/source/tutorials_use_cases.rst
  nbs/explore_huggingface_datasets.ipynb
  poetry.lock
  pyproject.toml
  tests/cyclops/data/__init__.py
  tests/cyclops/models/__init__.py
  tests/cyclops/models/wrappers/__init__.py
  tests/cyclops/monitor/test_clinical_applicator.py
  tests/cyclops/monitor/test_detector.py
  tests/cyclops/monitor/test_synthetic_applicator.py
  tests/cyclops/monitor/test_tester.py
  tests/cyclops/process/test_aggregate.py
  tests/cyclops/query/test_ops.py
  use_cases/mortality_prediction.ipynb
Labels: enhancement, code style, refactor

#475 Add codecov API token, small fixes to tutorials
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  docs/source/intro.rst
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  docs/source/tutorials_use_cases.rst
  poetry.lock
Labels: documentation

#478 Remove layout html, fix GEMINI wording in footer
  docs/source/_templates/layout.html
  docs/source/theme/footer.html
Labels: documentation
