Repository VectorInstitute/cyclops, pull requests merged in 2023-07, with the labels that each got.

#450 Fix tutotrial
  docs/source/tutorials/mimiciii/mortality_prediction.ipynb
Labels: documentation

#453 Limit queries to 100 rows to speed up docs build
  docs/source/tutorials/eicu/query_api.ipynb
  docs/source/tutorials/mimiciii/query_api.ipynb
  docs/source/tutorials/mimiciv/query_api.ipynb
  docs/source/tutorials/omop/query_api.ipynb
Labels: documentation

#456 Fix Report Package
  cyclops/report/model_card.py
  cyclops/report/report.py
  cyclops/report/templates/cyclops_generic_template_dark.jinja
  cyclops/report/templates/cyclops_generic_template_light.jinja
  docs/source/tutorials/mimiciii/mortality_prediction.ipynb
Labels: bug

#458 Add report API docs
  README.md
  docs/source/api.rst
  docs/source/intro.rst
  docs/source/reference/api/cyclops.report.rst
Labels: documentation

#460 Add github action for building and pushing docker image
  .github/workflows/docker.yml
  Dockerfile
Labels: enhancement

#459 Move Datasets to a Standalone Section
  cyclops/report/model_card.py
  cyclops/report/report.py
  cyclops/report/templates/cyclops_generic_template_light.jinja
  docs/source/tutorials/mimiciii/mortality_prediction.ipynb
Labels: bug, refactor

#462 Restructure Report Package
  cyclops/report/model_card/__init__.py
  cyclops/report/model_card/base.py
  cyclops/report/model_card/fields.py
  cyclops/report/model_card/model_card.py
  cyclops/report/model_card/sections.py
  cyclops/report/report.py
  cyclops/report/templates/cyclops_generic_template_light.jinja
  cyclops/report/utils.py
  docs/source/tutorials/mimiciii/mortality_prediction.ipynb
  poetry.lock
  pyproject.toml
Labels: refactor
