Repository VectorInstitute/cyclops, pull requests merged in 2023-10, with the labels that each got.

#490 Create __init__.py
  cyclops/tasks/__init__.py
Labels: bug

#491 Remove hydra use query api
  cyclops/query/base.py
  cyclops/query/configs/config.yaml
  cyclops/query/eicu.py
  cyclops/query/gemini.py
  cyclops/query/mimiciii.py
  cyclops/query/mimiciv.py
  cyclops/query/omop.py
  cyclops/query/orm.py
  poetry.lock
  pyproject.toml
  tests/cyclops/data/test_slicer.py
  tests/cyclops/query/test_base.py
  tests/cyclops/query/test_eicu.py
  tests/cyclops/query/test_interface.py
  tests/cyclops/query/test_mimiciv.py
  tests/cyclops/query/test_omop.py
  tests/cyclops/query/test_ops.py
  tests/cyclops/query/test_orm.py
Labels: bug, refactor

#492 Improve tests across vm
  tests/cyclops/query/test_ops.py
Labels: bug

#495 Remove query package to port as a new tool
  .github/workflows/code_checks.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  .github/workflows/package.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  cyclops/query/__init__.py
  cyclops/query/base.py
  cyclops/query/eicu.py
  cyclops/query/gemini.py
  cyclops/query/interface.py
  cyclops/query/mimiciii.py
  cyclops/query/mimiciv.py
  cyclops/query/omop.py
  cyclops/query/ops.py
  cyclops/query/orm.py
  cyclops/query/post_process/__init__.py
  cyclops/query/post_process/gemini.py
  cyclops/query/post_process/mimiciv.py
  cyclops/query/post_process/util.py
  cyclops/query/util.py
  docs/source/api.rst
  docs/source/conf.py
  docs/source/intro.rst
  docs/source/reference/api/cyclops.query.rst
  docs/source/tutorials.rst
  docs/source/tutorials/eicu/query_api.ipynb
  docs/source/tutorials/gemini/query_api.ipynb
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/mimiciii/query_api.ipynb
  docs/source/tutorials/mimiciv/query_api.ipynb
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/tutorials/nihcxr/monitor_api.ipynb
  docs/source/tutorials/omop/query_api.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  docs/source/tutorials_query.rst
  environment.yml
  poetry.lock
  pyproject.toml
  tests/cyclops/data/test_slicer.py
  tests/cyclops/query/__init__.py
  tests/cyclops/query/post_process/__init__.py
  tests/cyclops/query/post_process/test_util.py
  tests/cyclops/query/test_base.py
  tests/cyclops/query/test_eicu.py
  tests/cyclops/query/test_interface.py
  tests/cyclops/query/test_mimiciii.py
  tests/cyclops/query/test_mimiciv.py
  tests/cyclops/query/test_omop.py
  tests/cyclops/query/test_ops.py
  tests/cyclops/query/test_orm.py
  tests/cyclops/query/test_util.py
  tests/package/base.py
  tests/package/extras/models.py
  tests/package/extras/query.py
  tests/package/extras/report.py
Labels: refactor
