Repository VectorInstitute/cyclops, pull requests merged in 2024-05, with the labels that each got.

#597 Fix import_optional_module function to return NoneType
  cyclops/evaluate/metrics/experimental/metric_dict.py
  cyclops/models/torch_utils.py
  cyclops/utils/optional.py
Labels: bug

#600 Update tqdm
  poetry.lock
Labels: update

#606 Improve intersectional slicing
  cyclops/data/slicer.py
  tests/cyclops/data/test_slicer.py
Labels: enhancement, refactor

#612 Update codecov actions
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
Labels: ci

#613 Refactor slice functions and evaluators
  cyclops/data/slicer.py
  cyclops/data/utils.py
  cyclops/evaluate/evaluator.py
  cyclops/evaluate/fairness/evaluator.py
  cyclops/evaluate/utils.py
  cyclops/tasks/classification.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  tests/cyclops/data/test_slicer.py
  tests/cyclops/data/test_utils.py
  tests/cyclops/evaluate/test_utils.py
Labels: enhancement, refactor

#618 Fix comment in slicer docstring
  cyclops/data/slicer.py
Labels: documentation

#624 Try downgrading codecov action to resolve issue with upload
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
Labels: ci

#625 Add example of intersectional slicing to user guide
  docs/source/evaluation.rst
  docs/source/examples/metrics.ipynb
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
Labels: documentation

#620 Update pandas version and enable options
  cyclops/__init__.py
  cyclops/data/df/handle_types.py
  cyclops/data/df/vectorized.py
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  poetry.lock
  pyproject.toml
  tests/cyclops/data/df/test_handle_types.py
Labels: dependencies

#626 Add new tutorial notebook for workshop
  docs/source/tutorials/diabetes_130/readmission_prediction.ipynb
  docs/source/tutorials_use_cases.rst
Labels: documentation
