Repository VectorInstitute/cyclops, pull requests merged in 2024-02, with the labels that each got.

#551 Update to pillow 10.0 which has important security fixes
  .pre-commit-config.yaml
  cyclops/models/catalog.py
  poetry.lock
  pyproject.toml
Labels: update

#543 Improve documentation for evaluate package
  README.md
  docs/source/_static/css/cyclops.css
  docs/source/_static/cyclops_logo-dark.png
  docs/source/_static/cyclops_logo.png
  docs/source/_static/favicon.ico
  docs/source/_static/logos/gemini_logo.png
  docs/source/_static/logos/vector_logo.png
  docs/source/_templates/sections/footer.html
  docs/source/api.rst
  docs/source/conf.py
  docs/source/developing.rst
  docs/source/evaluation.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/intro.rst
  docs/source/model_report.rst
  docs/source/monitoring.rst
  docs/source/reference/api/cyclops.evaluate.rst
  docs/source/reference/api/evaluator.rst
  docs/source/reference/api/fairness_evaluator.rst
  docs/source/reference/api/metrics.rst
  docs/source/reference/api/metrics/accuracy.rst
  docs/source/reference/api/metrics/auroc.rst
  docs/source/reference/api/metrics/average_precision.rst
  docs/source/reference/api/metrics/f1score.rst
  docs/source/reference/api/metrics/f_beta.rst
  docs/source/reference/api/metrics/precision.rst
  docs/source/reference/api/metrics/precision_recall_curve.rst
  docs/source/reference/api/metrics/recall.rst
  docs/source/reference/api/metrics/roc.rst
  docs/source/reference/api/metrics/sensitivity.rst
  docs/source/reference/api/metrics/specificity.rst
  docs/source/reference/api/metrics/stat_scores.rst
  docs/source/theme/breadcrumbs.html
  docs/source/theme/footer.html
  docs/source/theme/layout.html
  docs/source/theme/static/css/cyclops.css
  docs/source/theme/static/js/theme.js
  docs/source/theme/theme.conf
  docs/source/tutorials.rst
  docs/source/tutorials/nihcxr/cxr_classification.ipynb
  docs/source/user_guide.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#552 Small fix to readme, and contributing docs
  README.md
  docs/source/contributing.rst
  docs/source/installation.rst
Labels: documentation

#554 Apply ruff formatter and ditch black
  .pre-commit-config.yaml
  cyclops/data/df/handle_types.py
  cyclops/data/slicer.py
  cyclops/evaluate/evaluator.py
  cyclops/evaluate/fairness/evaluator.py
  cyclops/evaluate/metrics/accuracy.py
  cyclops/evaluate/metrics/auroc.py
  cyclops/evaluate/metrics/experimental/accuracy.py
  cyclops/evaluate/metrics/experimental/auroc.py
  cyclops/evaluate/metrics/experimental/average_precision.py
  cyclops/evaluate/metrics/experimental/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/f_score.py
  cyclops/evaluate/metrics/experimental/functional/accuracy.py
  cyclops/evaluate/metrics/experimental/functional/auroc.py
  cyclops/evaluate/metrics/experimental/functional/average_precision.py
  cyclops/evaluate/metrics/experimental/functional/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/functional/f_score.py
  cyclops/evaluate/metrics/experimental/functional/mae.py
  cyclops/evaluate/metrics/experimental/functional/mape.py
  cyclops/evaluate/metrics/experimental/functional/mse.py
  cyclops/evaluate/metrics/experimental/functional/negative_predictive_value.py
  cyclops/evaluate/metrics/experimental/functional/precision_recall.py
  cyclops/evaluate/metrics/experimental/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/experimental/functional/roc.py
  cyclops/evaluate/metrics/experimental/functional/smape.py
  cyclops/evaluate/metrics/experimental/functional/specificity.py
  cyclops/evaluate/metrics/experimental/mae.py
  cyclops/evaluate/metrics/experimental/mape.py
  cyclops/evaluate/metrics/experimental/metric.py
  cyclops/evaluate/metrics/experimental/metric_dict.py
  cyclops/evaluate/metrics/experimental/mse.py
  cyclops/evaluate/metrics/experimental/negative_predictive_value.py
  cyclops/evaluate/metrics/experimental/precision_recall.py
  cyclops/evaluate/metrics/experimental/precision_recall_curve.py
  cyclops/evaluate/metrics/experimental/roc.py
  cyclops/evaluate/metrics/experimental/smape.py
  cyclops/evaluate/metrics/experimental/specificity.py
  cyclops/evaluate/metrics/experimental/wmape.py
  cyclops/evaluate/metrics/f_beta.py
  cyclops/evaluate/metrics/functional/auroc.py
  cyclops/evaluate/metrics/functional/precision_recall.py
  cyclops/evaluate/metrics/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/functional/roc.py
  cyclops/evaluate/metrics/functional/sensitivity.py
  cyclops/evaluate/metrics/functional/specificity.py
  cyclops/evaluate/metrics/precision_recall.py
  cyclops/evaluate/metrics/precision_recall_curve.py
  cyclops/evaluate/metrics/roc.py
  cyclops/evaluate/metrics/sensitivity.py
  cyclops/evaluate/metrics/specificity.py
  cyclops/evaluate/metrics/stat_scores.py
  cyclops/models/wrappers/pt_model.py
  cyclops/report/report.py
  cyclops/tasks/utils.py
  docs/source/contributing.rst
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_mpi4py.py
Labels: code style

#556 Update github actions to latest release versions
  .github/workflows/code_checks.yml
  .github/workflows/docker.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  .github/workflows/package.yml
  .github/workflows/publish.yml
  pyproject.toml
Labels: update

#557 Small fix to docs deploy poetry install, update contrib md
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  CONTRIBUTING.md
Labels: documentation, ci

#559 Move jinja macros to separate file for readability
  cyclops/report/templates/cyclops_generic_template.jinja
  cyclops/report/templates/macros.jinja
Labels: refactor

#563 Add pip audit to code check workflow
  .github/workflows/code_checks.yml
  poetry.lock
  pyproject.toml
Labels: ci

#565 Use furo sphinx theme in line with aieng-template
  docs/source/_static/css/cyclops.css
  docs/source/_templates/sections/footer.html
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/api/cyclops.data.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#567 First pass at refactoring jinja template
  cyclops/report/report.py
  cyclops/report/templates/cyclops_generic_template.jinja
  cyclops/report/templates/model_report/button.js
  cyclops/report/templates/model_report/macros.jinja
  cyclops/report/templates/model_report/model_report.jinja
  cyclops/report/templates/model_report/plot.js
Labels: refactor

#568 Small fixes to discharge prediction notebook
  .github/workflows/docs_build.yml
  .github/workflows/integration_tests.yml
  benchmarks/mimiciv/discharge_prediction.ipynb
  benchmarks/mimiciv/icu_mortality_prediction.ipynb
  docs/source/tutorials/nihcxr/monitor_api.ipynb
Labels: bug, refactor
