Repository VectorInstitute/cyclops, pull requests merged in 2024-06, with the labels that each got.

#639 Confidence interval feature
  cyclops/report/model_card/sections.py
  cyclops/report/report.py
  cyclops/report/templates/model_report/macros.jinja
  cyclops/report/templates/model_report/model_report.jinja
  cyclops/report/templates/model_report/plot.js
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  poetry.lock
Labels: enhancement

#641 Add explicit __all__ declaration to specify public API
  cyclops/evaluate/__init__.py
  cyclops/evaluate/metrics/__init__.py
  cyclops/evaluate/metrics/experimental/__init__.py
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/functional/__init__.py
Labels: code style

#646 Unify docs workflows
  .github/workflows/docs.yml
  .github/workflows/docs_release.yml
  .github/workflows/integration_tests.yml
  docs/Makefile
  docs/source/conf.py
Labels: ci

#648 Release v0.2.10
  .github/workflows/docs_release.yml
  poetry.lock
  pyproject.toml
Labels: release
