Repository VectorInstitute/cyclops, pull requests merged in 2024-03, with the labels that each got.

#573 Extend to python 3.11 support
  poetry.lock
  pyproject.toml
Labels: update

#574 Use namedtuple to store curve results (ROC, PR) for non-experimental …
  cyclops/evaluate/metrics/functional/__init__.py
  cyclops/evaluate/metrics/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/functional/roc.py
  cyclops/evaluate/metrics/precision_recall_curve.py
  cyclops/evaluate/metrics/roc.py
  cyclops/evaluate/metrics/utils.py
  cyclops/report/plot/classification.py
Labels: bug

#572 Use namedtuple to store curve results (ROC, PR)
  cyclops/evaluate/metrics/experimental/functional/__init__.py
  cyclops/evaluate/metrics/experimental/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/experimental/functional/roc.py
  cyclops/evaluate/metrics/experimental/precision_recall_curve.py
  cyclops/evaluate/metrics/experimental/roc.py
  cyclops/evaluate/metrics/functional/__init__.py
  cyclops/evaluate/metrics/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/functional/roc.py
  cyclops/evaluate/metrics/precision_recall_curve.py
  cyclops/evaluate/metrics/roc.py
  cyclops/evaluate/metrics/utils.py
  cyclops/report/plot/classification.py
Labels: refactor

#570 Test report module
  tests/cyclops/report/plot/test_classification_plotter.py
Labels: tests

#575 Add threshperf plot, tests and example use
  cyclops/report/plot/classification.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  tests/cyclops/report/plot/test_classification_plotter.py
Labels: enhancement

#580 Update dependencies
  poetry.lock
  pyproject.toml
Labels: update

#579 Add ability to truncate report and centralise report generation.
  cyclops/report/model_card/fields.py
  cyclops/report/model_card/sections.py
  cyclops/report/report.py
  cyclops/report/templates/model_report/macros.jinja
  cyclops/report/templates/model_report/model_report.jinja
  cyclops/report/templates/model_report/plot.js
  cyclops/report/utils.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  tests/cyclops/report/test_utils.py
Labels: enhancement

#581 fix typos
  benchmarks/mimiciv/discharge_prediction.ipynb
  benchmarks/mimiciv/icu_mortality_prediction.ipynb
  cyclops/data/aggregate.py
  cyclops/data/clean.py
  cyclops/data/df/feature.py
  cyclops/data/df/normalize.py
  cyclops/data/df/split.py
  cyclops/data/impute.py
  cyclops/evaluate/metrics/experimental/distributed_backends/mpi4py.py
  cyclops/evaluate/metrics/experimental/distributed_backends/torch_distributed.py
  cyclops/evaluate/metrics/experimental/roc.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  cyclops/evaluate/metrics/functional/stat_scores.py
  cyclops/models/wrappers/base.py
  cyclops/models/wrappers/pt_model.py
  cyclops/models/wrappers/sk_model.py
  cyclops/monitor/plotter.py
  cyclops/monitor/synthetic_applicator.py
  cyclops/report/plot/classification.py
  cyclops/report/report.py
  cyclops/tasks/base.py
  cyclops/utils/file.py
  cyclops/utils/log.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/mimiciv/mortality_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  nbs/explore_huggingface_datasets.ipynb
  nbs/monitor/gemini_drift_experiments/feature_shift.ipynb
  nbs/monitor/mortality/preprocessing.ipynb
  tests/cyclops/data/df/test_split.py
  tests/cyclops/data/df/test_vectorized.py
  tests/cyclops/data/test_clean.py
  tests/cyclops/evaluate/metrics/experimental/test_negative_predictive_value.py
Labels: documentation, refactor

#585 Fix report single metric
  cyclops/report/report.py
Labels: bug

#588 Fix copy on type change
  cyclops/evaluate/metrics/experimental/functional/auroc.py
  cyclops/evaluate/metrics/experimental/functional/average_precision.py
  cyclops/evaluate/metrics/experimental/functional/confusion_matrix.py
  cyclops/evaluate/metrics/experimental/functional/f_score.py
  cyclops/evaluate/metrics/experimental/functional/mae.py
  cyclops/evaluate/metrics/experimental/functional/matthews_corr_coef.py
  cyclops/evaluate/metrics/experimental/functional/precision_recall_curve.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_mpi4py.py
Labels: refactor
