Repository VectorInstitute/cyclops, pull requests merged in 2024-04, with the labels that each got.

#590 Update `array-api-compat` version
  .gitignore
  cyclops/evaluate/metrics/experimental/functional/auroc.py
  cyclops/evaluate/metrics/experimental/functional/average_precision.py
  cyclops/evaluate/metrics/experimental/utils/ops.py
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/metrics/experimental/test_mean_error.py
  tests/cyclops/evaluate/metrics/experimental/utils/test_ops.py
Labels: refactor, update

#587 Add support for plotting calibration curve
  cyclops/report/plot/classification.py
  docs/source/tutorials/kaggle/heart_failure_prediction.ipynb
  docs/source/tutorials/synthea/los_prediction.ipynb
  poetry.lock
  tests/cyclops/report/plot/test_classification_plotter.py
Labels: enhancement

#591 Add js deps to fix plotly rendering
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  docs/source/_static/custom.js
  docs/source/_static/require.min.js
Labels: documentation

#593 Remove use of get_device in base task class
  cyclops/tasks/base.py
  tests/package/base.py
Labels: bug, tests

#592 Update `deploy/README.md`
  deploy/README.md
  deploy/bentofile.yaml
  deploy/service.py
  poetry.lock
  pyproject.toml
Labels: bug, documentation, refactor

#594 Adjust integration test workflow to run on cyclops vm runner
  .github/workflows/integration_tests.yml
  poetry.lock
  pyproject.toml
  tests/cyclops/evaluate/metrics/conftest.py
  tests/cyclops/evaluate/metrics/experimental/distributed_backends/test_mpi4py.py
Labels: ci

#596 Add test parallelization
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: update, ci

#595 Upgrade `datasets`
  .pre-commit-config.yaml
  README.md
  docs/source/conf.py
  poetry.lock
  pyproject.toml
Labels: update

#589 Add report user guide notebook
  docs/source/evaluation.rst
  docs/source/examples/report.ipynb
  docs/source/model_report.rst
  docs/source/monitoring.rst
  docs/source/user_guide.rst
Labels: documentation

#599 Reduce number of workers for running tests
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/integration_tests.yml
  tests/conftest.py
Labels: ci
